services:
  rest-api2-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: rest_api2_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - rest-api2-postgres-data:/var/lib/postgresql/data
    ports:
      - "5455:5432"
    networks:
      - rest-api2-network

  rest-api2-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rest-api2-postgres:5432/rest_api2_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - rest-api2-postgres
    networks:
      - rest-api2-network

volumes:
  rest-api2-postgres-data:
networks:
  rest-api2-network:
    driver: bridge